### ISSUE TITLE
can't render lists without bullets or numbers

### ISSUE THREAD

**Issue by nebster** [publiccodenet/jekyll-theme#10]
on the people template for instance, we need to stack attributes without list layout

**Comment by bvhme** [comment]
I would like to deprioritize this as I think making exceptions to the HTML5 specification for structuring content will limit us in transposing and transforming content. The specification offers us the following list types:

* [Ordered lists](https://www.w3.org/TR/html52/grouping-content.html#the-ol-element)
* [Unordered lists](https://www.w3.org/TR/html52/grouping-content.html#the-ul-element)
* [Description lists](https://www.w3.org/TR/html52/grouping-content.html#the-dl-element)

I understand this is a limitation.
