### ISSUE TITLE
Navigation across subdomains, whitespace, breadcrumbs

### ISSUE THREAD

**Issue by nebster** [publiccodenet/jekyll-theme#14]
Often the page subtitles are so large they take up all the space above the fold.  We need a standardized way to use titling and breadcrumbs to provide wayfinding without pushing content too far down.

**Comment by bvhme** [comment]
I have tried to improve this with recent changes. @nebster, would you say this is now better?

**Comment by bvhme** [comment]
Closing for now but will reopen if this is still the case, not in my testing.
