### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/jekyll-theme#16]
As part of [About issue #244](https://github.com/publiccodenet/about/issues/244), I propose updating the footer across all of our websites.

One approach would be to grab the 'contact' block on the HTTP site. 

I suggest updating this content with:

## Contact 
* [Contact us](https://about.publiccode.net/organization/contact-details) - we'd love your feedback.

The Foundation for Public Code Vereninging is registered as an association (vereniging met volledige rechtsbevoegdheid) under Dutch law. Our chamber of commerce (KvK) registration number is 74996452.

**Comment by bvhme** [comment]
I'd suggest framing it as some information about the publishing institution:

> Published June 14th, 2019 by the _Foundation for Public Code Vereninging met volledige rechtsbevoegdheid_, an association under Dutch law, registered at the chamber of commerce in Amsterdam (KvK) under number 74996452.
> 
> * [About us](https://about.publiccode.net/)
> * [Contact details](https://about.publiccode.net/organization/contact-details)

This makes it clear what the information is, why it is there and what relationship it has to the content. This is just a suggestion though.

**Comment by bvhme** [comment]
Fixed in ee9deb6.
