### ISSUE TITLE
Repetitive footer

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/jekyll-theme#41]
I don't think the links I've circled in purple add anything.

<img width="1153" alt="Screen Shot 2020-08-14 at 12 29 53" src="https://user-images.githubusercontent.com/5113815/90240782-30fb7500-de2a-11ea-9954-e5802ded3006.png">

**Comment by ElenaFdR** [comment]
Closed by #52.

**Comment by ElenaFdR** [comment]
I am mistaken.

**Comment by angelplasma** [comment]
Changes from https://github.com/publiccodenet/publiccode.net/issues/133 will not affect/be replicated in the footer nav
