### ISSUE TITLE
Update top nav

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/jekyll-theme#57]
The current top nav on publiccode.net links to our other repos, but doesn't provide any context to suggest you're navigating to a separate website.

Separately, one convention for websites that represent a Github repo is to include a link to the Github repo in the top right corner of the website (often represented by the Octocat).

We propose the following top nav instead, which includes our most important links, most of which are to pages within this repo.

**Comment by Ainali** [comment]
Is this top nav configurable or will it be the same on About, Blog and Standard?

**Comment by angelplasma** [comment]
@Ainali Would love to hear your thoughts on desirable configurations.

Our thought was to update the universal nav to be more useful now, and then explore context-specific modularity.

**Comment by Ainali** [comment]
I don't have any ideas, but if they are the same, wouldn't this still be the case?

> The current top nav on publiccode.net links to our other repos, but doesn't provide any context to suggest you're navigating to a separate website.

For example, from the blog all the top nav bar links would still go to another website. So even though we improve the links and fix the GitHub link we might still have one problem to solve.

**Comment by angelplasma** [comment]
Very true that links to other repos would continue to lack aforementioned context. 

However—and I say this not yet having tested my assumptions + talked to enough of the team—I am not so sure the differences between repos/subdomains are currently so meaningful to most users that they need special prefacing...

Would love to hear more on the need for clear repo dividers—this is certainly an area of exploration for the upcoming site architecture conversation.

**Comment by Ainali** [comment]
I think you are right there, it might not be a very meaningful division for users as such. What could matter though, is that once you leave the blog for the website, it is not obvious how to navigate back.
