### ISSUE TITLE
extra characters in Foundation name in top nav on publiccode.net 404 page 

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/jekyll-theme#60]
Discovered when locally built.
This doesn't happen on any other page on the repo.

<img width="614" alt="Screen Shot 2021-01-28 at 21 37 27" src="https://user-images.githubusercontent.com/5113815/106196315-931a1d80-61b1-11eb-8262-ff95df0b5e99.png">

Inspecting the element using dev tools:
<img width="649" alt="Screen Shot 2021-01-28 at 21 40 21" src="https://user-images.githubusercontent.com/5113815/106196269-85649800-61b1-11eb-9120-33c3480482b1.png">

**Comment by bvhme** [comment]
This is an encoding error on the non-breaking spaces in the name, it can be solved by making sure the encoding is set to UTF-8
