### ISSUE TITLE
Implement GDPR compliant web analysis tool 

### ISSUE THREAD

**Issue by felixfaassen** [publiccodenet/jekyll-theme#64]
In our logframe : https://about.publiccode.net/organization/measurable-goals

The following outcome has been set for 2021 quarter 1:

Our community keeps engaging with us and grows
    Baseline: no analytics
   Target: set up analytics
    Means of verification: tracking engagement through: recurring community call participants, being @’d in conversations, resharing our content, total numbers growing month on month

In order to reach this goal I would like to test out 1 or more GDPR, privacy oriented web analytics tools preferably open-source.
Wish list
- [x] does not track users
- [x] does not share data with others
- [x] Does not use cookies
- [x] Is preferably open-source

https://plausible.io is one that thicks all the boxes

Our online website assets: about, standard and our publiccode.net all share the same jekyll-theme. 

This issue will be used to test out different tools and make a decision so we can measure how or content online is used.

More info about how plausible compares to other tools:
- https://plausible.io/vs-google-analytics
- https://plausible.io/vs-matomo

**Comment by ElenaFdR** [comment]
@felixfaassen Did you have any thoughts on how long to run Plausible as a test? I suggest 2 months, then a review on whether it's meeting our needs well enough.

cc @angelplasma Let's update the PRD to reflect the stats Plausible will give us?

**Comment by ElenaFdR** [comment]
The only thing I haven't seen yet in the Plausible docs is user journeys across site tracking, but that's probably fine. (@angelplasma, you suggested yesterday that "all pages on publiccode.net see regular traffic" could be an alternative goal.)

**Comment by felixfaassen** [comment]
I leave this issue open until we have selected and implemented a final solution.
@ElenaFdR the dashboards can be shared privately but also publicly ;-) 

As we are in testing phase I have made our dashboard public:
- https://plausible.io/publiccode.net

As for the test, I leave this up for you consideration ;-) I think it is nice to test it for 2 months. We have a free trial of 30 days

**Comment by ElenaFdR** [comment]
Re set up: can we block staff IP addresses? Can you give me access to set up goal conversions? Are there more data download options when you're logged in (or an API) so we can track individual page performance over time?

**Comment by Ainali** [comment]
Should this issue be closed?

**Comment by Ainali** [comment]
I think we can consider this as not an experiment anymore, closing as complete.
