### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by ElenaFdR** [publiccodenet/jekyll-theme#66]
In order to bring our Jekyll theme repo branch naming in line with all of our other repos (as per [About repo issue #668](https://github.com/publiccodenet/about/issues/668)).

This can only be done after [Jekyll remote theme issue 84](https://github.com/benbalter/jekyll-remote-theme/issues/84) is resolved.

**Comment by bvhme** [comment]
I've subscribed to that issue and will re-open when it is resolved.

**Comment by bvhme** [comment]
This is now done!
