### ISSUE TITLE
Declutter by removing duplicate link in the same footer section

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/jekyll-theme#81]
As identified in publiccodenet/about#1105 in the [footer.liquid](https://github.com/publiccodenet/jekyll-theme/blob/master/_includes/footer.liquid) we generate a link to the repository twice in the "GitHub repository information" section. I suggest  we remove `<li><a href="{{ site.github.repository_url }}">Content and code</a></li>` and just have the link that is explained with a sentence left (`<a href="{{ site.github.repository_url }}">{{ site.github.repository_nwo }}</a>`).

**Comment by ElenaFdR** [comment]
I still propose we get rid of all 3 bullets, as experienced users will navigate via the universal nav or footer and novice users will be invited by the 'edit this page' buttons in the right nav.

- [Content and code](https://github.com/publiccodenet/about)
- [Issues](https://github.com/publiccodenet/about/issues/)
- [Pull requests](https://github.com/publiccodenet/about/pulls/)
